version: '3.3'

services:
  db:
    image: mysql:latest
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 9784rgsoe97g
      MYSQL_DATABASE: nymph_example
      MYSQL_USER: nymph_example
      MYSQL_PASSWORD: omgomg

  pubsub:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-pubsub
    volumes:
      - type: bind
        source: .
        target: /var/nymph
    command: ["./wait-for-it.sh", "db:3306", "--", "php", "/var/nymph/examples/examples/pubsub.php"]
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: nymph_example
      MYSQL_USER: nymph_example
      MYSQL_PASSWORD: omgomg

  web:
    depends_on:
      - db
      - pubsub
    build:
      context: .
      dockerfile: Dockerfile-web
    volumes:
      - type: bind
        source: .
        target: /var/www/html
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: nymph_example
      MYSQL_USER: nymph_example
      MYSQL_PASSWORD: omgomg
      PUBSUB_HOST: pubsub:8081
